## 20 nm sphere with parameters to match Drude Au in BEM with a 20 nm sphere
##
general:

  dipole_orientation: 
    - 1.  # x, parallel to separation
    - 0.  # y, perpendiculat
    - 0.  # z

  # seperation specifics
  min_sep: !!float 50e-7 ## in cm
  max_sep: !!float 350e-7 
  sep_step_size: !!float 1e-7
  
  min_energy: 2.0
  max_energy: 3.0
  freq_step_size: 0.001

  drive_amp: !!float 30  # strength of electron field 40 nm away
  # drive_energy: 2.6 # eV, or 515 nm for gold 80 nm vacuum

  background_ref_index: 1.


plasmon:  

  radius: !!float 40e-7  # centimeters

  ## I think unused for calculation if fit parameters are called below
  drude_damping_energy: 0.066
  # drude_damping_energy: 0.06689  ## added 10% to drude damping to simulate radiation damping
  plasma_energy: 9.0705  # eV
  eps_inf: 10

  incorperate_parameters_from_fit: True
  ## fit parameters with explicity static contribution (013018)
  ## no mass in static alpha
  fit_mass: 0.07558 ## multiplied by 10^-32
  fit_hbar_gamma: 0.06327
  fit_hbar_w0: 2.548
  
  ## Quadrupole
  include_quadrupole: False
  # 
  fit_l2_mass: 4.778 ## multiplied by 10^-32
  fit_l2_hbar_gamma: 0.06617
  fit_hbar_w2: 2.661


fluorophore:  # values for ATTO 532, modified to vacuum

  res_energy: 2.6 # eV, or 562 nm: value of maximum fluorescence emission
  extinction_coeff: !!float 200e3 # L/mol*cm
  # extinction_coeff: !!float 200e4 # L/mol*cm
  lifetime: !!float 38e-10 # ns
  lw_gamma: 0.075
  mass_gamma: 0.075
  # mass_gamma: 0.066
